permissionInformation={
  {
    icon=R.drawable.ic_file_outline,
    title="读取/修改或删除您共享存储空间中的内容";
    summary="我TM也不知道干什么的，不给调试时会出一些小Bug；使用时可以不给，不影响";
    permissions={"android.permission.INTERNET","android.permission.ACCESS_NETWORK_STATE","android.permission.ACCESS_WIFI_STATE"};
  },
  {
    icon=R.drawable.ic_language_outline,
    title="完全的网络访问权限";
    summary="用于连接狠活服务器";
    permissions={"android.permission.INTERNET","android.permission.ACCESS_NETWORK_STATE","android.permission.ACCESS_WIFI_STATE"};
  },
{
    icon=R.drawable.ic_wifi_outline,
    title="查看网络连接、查看WLAN连接";
    summary="用于检测抓包，防止某些贵物把狠活（特别是关于李龟黏的）外泄";
    permissions={"android.permission.INTERNET","android.permission.ACCESS_NETWORK_STATE","android.permission.ACCESS_WIFI_STATE"};
  },
}
 